name: Test TensorLy-Gcp

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with pytest and coverage
      run: |
        pytest -vvv --cov=tlgcp --cov-report=xml
    - name: Check coverage with CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        verbose: true
